version: '3'
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data/mongodb:/data/db
  minio:
    image: minio/minio
    restart: always
    environment:
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: password
    ports:
      - 9000:9000
    volumes:
      - ./data/minio:/data
    command: server /data
